create table user_accounts (
    id bigint generated by default as identity,
    email varchar(180) not null,
    display_name varchar(120) not null,
    password_hash varchar(128) not null,
    constraint pk_user_accounts primary key (id),
    constraint uk_user_accounts_email unique (email)
);

create table user_account_roles (
    user_id bigint not null,
    role varchar(32) not null,
    constraint pk_user_account_roles primary key (user_id, role),
    constraint fk_user_account_roles_user foreign key (user_id) references user_accounts (id) on delete cascade
);

create table catalog_titles (
    id bigint generated by default as identity,
    slug varchar(120) not null,
    title varchar(180) not null,
    type varchar(20) not null,
    release_year integer not null,
    maturity_rating varchar(20) not null,
    runtime_minutes integer not null,
    tagline varchar(240) not null,
    synopsis varchar(2000) not null,
    poster_path varchar(260) not null,
    backdrop_path varchar(260) not null,
    display_priority integer not null,
    constraint pk_catalog_titles primary key (id),
    constraint uk_catalog_titles_slug unique (slug),
    constraint ck_catalog_titles_type check (type in ('MOVIE', 'SERIES'))
);

create table catalog_title_genres (
    title_id bigint not null,
    genre varchar(80) not null,
    constraint pk_catalog_title_genres primary key (title_id, genre),
    constraint fk_catalog_title_genres_title foreign key (title_id) references catalog_titles (id) on delete cascade
);

create table catalog_videos (
    id bigint generated by default as identity,
    title_id bigint not null,
    season_number integer not null,
    episode_number integer not null,
    label varchar(120) not null,
    video_title varchar(180) not null,
    duration_seconds integer not null,
    asset_filename varchar(220) not null,
    subtitle_filename varchar(220) not null,
    constraint pk_catalog_videos primary key (id),
    constraint fk_catalog_videos_title foreign key (title_id) references catalog_titles (id) on delete cascade
);

create table media_assets (
    id bigint generated by default as identity,
    video_id bigint not null,
    original_filename varchar(220) not null,
    original_upload_name varchar(220) not null,
    content_sha256 varchar(64),
    content_type varchar(120),
    size_bytes bigint not null,
    hls_master_path varchar(220),
    thumbnail_manifest_path varchar(220),
    status varchar(24) not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_media_assets primary key (id),
    constraint uk_media_assets_video unique (video_id),
    constraint ck_media_assets_status check (status in ('REGISTERED', 'READY', 'MISSING', 'FAILED')),
    constraint fk_media_assets_video foreign key (video_id) references catalog_videos (id) on delete cascade
);

create table transcode_jobs (
    id bigint generated by default as identity,
    video_id bigint not null,
    status varchar(24) not null,
    progress_percent integer not null,
    force boolean not null,
    requested_at timestamp(6) with time zone not null,
    started_at timestamp(6) with time zone,
    finished_at timestamp(6) with time zone,
    message varchar(1200),
    output_path varchar(500),
    constraint pk_transcode_jobs primary key (id),
    constraint ck_transcode_jobs_status check (status in ('PENDING', 'RUNNING', 'DONE', 'FAILED')),
    constraint fk_transcode_jobs_video foreign key (video_id) references catalog_videos (id) on delete cascade
);

create table watchlist_items (
    id bigint generated by default as identity,
    user_id bigint not null,
    title_id bigint not null,
    created_at timestamp(6) with time zone not null,
    constraint pk_watchlist_items primary key (id),
    constraint uk_watchlist_user_title unique (user_id, title_id),
    constraint fk_watchlist_items_user foreign key (user_id) references user_accounts (id) on delete cascade,
    constraint fk_watchlist_items_title foreign key (title_id) references catalog_titles (id) on delete cascade
);

create table user_progress (
    id bigint generated by default as identity,
    user_id bigint not null,
    video_id bigint not null,
    position_seconds integer not null,
    duration_seconds integer not null,
    completed boolean not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_user_progress primary key (id),
    constraint uk_progress_user_video unique (user_id, video_id),
    constraint fk_user_progress_user foreign key (user_id) references user_accounts (id) on delete cascade,
    constraint fk_user_progress_video foreign key (video_id) references catalog_videos (id) on delete cascade
);

create index idx_catalog_title_genres_title on catalog_title_genres (title_id);
create index idx_catalog_title_genres_genre on catalog_title_genres (genre);
create index idx_catalog_videos_title_order on catalog_videos (title_id, season_number, episode_number, id);
create index idx_media_assets_content_sha256 on media_assets (content_sha256);
create index idx_transcode_jobs_requested_at on transcode_jobs (requested_at desc);
create index idx_transcode_jobs_video on transcode_jobs (video_id);
create index idx_watchlist_items_user on watchlist_items (user_id);
create index idx_watchlist_items_title on watchlist_items (title_id);
create index idx_user_progress_user_updated on user_progress (user_id, updated_at desc);
create index idx_user_progress_video on user_progress (video_id);
